version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: /etc/myportfolio/env.conf
    ports:
      - "80:80"
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file: /etc/myportfolio/env.conf
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dbdata:
