version: '2.1'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: /etc/myportfolio/env.conf
    ports:
      - "5002:80"
    links:
      - db:db
    depends_on:
      db:
       condition: service_healthy
    volumes:
      - media:/portfoliomedia
  db:
    image: postgres
    restart: always
    env_file: /etc/myportfolio/env.conf
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c
            '\\l'"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  dbdata:
  media:
