# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 04:10
from __future__ import unicode_literals

import animalapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('', 'Select species...'), ('dog', 'dog'), ('cat', 'cat')], default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('id_number', models.CharField(default='', max_length=50, unique=True)),
                ('gender', models.BooleanField()),
                ('birthday', models.DateField()),
                ('surgery', models.BooleanField(verbose_name='Spayed/neutered')),
                ('vaccine', models.BooleanField(verbose_name='Vaccinated')),
                ('location', models.CharField(choices=[('OFOSA shelter', 'OFOSA shelter'), ('PetSmart Tanasbourne', 'PetSmart Tanasbourne'), ('PetSmart Wilsonville', 'PetSmart Wilsonville'), ('PetSmart Cedar Hills', 'PetSmart Cedar Hills'), ('PetSmart Hillsboro', 'PetSmart Hillsboro'), ('Foster home', 'Foster home')], default='', max_length=50)),
                ('intake_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'available'), ('temporarily unavailable', 'temporarily unavailable'), ('on hold', 'on hold'), ('ADOPTED', 'ADOPTED')], default='available', max_length=20)),
                ('home', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cats', 'cats'), ('dogs', 'dogs'), ('other pets', 'other pets'), ('young children', 'young children')], default='', max_length=255, verbose_name='Prefers a home without (optional)')),
                ('notes', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=animalapp.models.upload_pet_image)),
                ('alt', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cat', serialize=False, to='animalapp.Animal')),
                ('cat_breed', models.CharField(choices=[('American Shorthair', 'American Shorthair'), ('Birman', 'Birman'), ('Domestic Shorthair/Mix', 'Domestic Shorthair/Mix'), ('Maine Coon', 'Maine Coon'), ('Oriental', 'Oriental'), ('Persian', 'Persian'), ('Ragdoll', 'Ragdoll'), ('Siamese', 'Siamese'), ('Siamese/Mix', 'Siamese/Mix'), ('Sphynx', 'Sphynx')], default='Domestic Shorthair/Mix', max_length=50)),
                ('cat_color', models.CharField(blank=True, choices=[('black', 'black'), ('brown', 'brown'), ('calico', 'calico'), ('gray', 'gray'), ('orange', 'orange'), ('seal point', 'seal point'), ('tabby', 'tabby'), ('tabby orange', 'tabby orange'), ('tabby white', 'tabby white'), ('tortoiseshell', 'tortoiseshell'), ('tuxedo', 'tuxedo'), ('white', 'white')], default='', max_length=255)),
                ('cat_personality', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('very playful', 'very playful'), ('sociable and outgoing', 'sociable and outgoing'), ('cuddly and affectionate', 'cuddly and affectionate'), ('independent', 'independent'), ('calm', 'calm'), ('a bit shy in the shelter environment', 'a bit shy in the shelter environment'), ('loves to be around people', 'loves to be around people'), ('adores brushing', 'adores brushing'), ('needs a quiet home', 'needs a quiet home'), ('needs love and consistency', 'needs love and consistency'), ('appreciates lots of attention', 'appreciates lots of attention'), ('talkative', 'talkative'), ('not shy about looking for attention', 'not shy about looking for attention'), ('sweet and gentle', 'sweet and gentle')], default='', max_length=293)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dog', serialize=False, to='animalapp.Animal')),
                ('dog_breed', models.CharField(blank=True, choices=[('Beagle', 'Beagle'), ('Boxer', 'Boxer'), ('Bulldog', 'Bulldog'), ('Chihuahua', 'Chihuahua'), ('Dachshund', 'Dachshund'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Labrador Retriever', 'Labrador Retriever'), ('Labrador/Mix', 'Labrador/Mix'), ('Miniature Schnauzer', 'Miniature Schnauzer'), ('Poodle', 'Poodle'), ('Shepherd/Mix', 'Shepherd/Mix'), ('Shih Tzu', 'Shih Tzu'), ('Spaniel/Mix', 'Spaniel/Mix'), ('Terrier/Mix', 'Terrier/Mix'), ('Yorkshire Terrier', 'Yorkshire Terrier')], default='', max_length=50)),
                ('size', models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='', max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, default='', max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Specify weight (optional)')),
                ('dog_color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('black', 'black'), ('brown', 'brown'), ('tan', 'tan'), ('white', 'white')], default='', max_length=21)),
                ('dog_personality', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('friendly and affectionate', 'friendly and affectionate'), ('sociable and outgoing', 'sociable and outgoing'), ('profoundly loyal', 'profoundly loyal'), ('house-trained', 'house-trained'), ('cuddly and affectionate', 'cuddly and affectionate'), ('frequent training sessions', 'frequent training sessions'), ('friendly toward strangers', 'friendly toward strangers'), ('has a quiet, laid-back temperament', 'has a quiet, laid-back temperament'), ('loves running around and playing', 'loves running around and playing'), ('not very fond of the outdoors', 'not very fond of the outdoors')], default='', max_length=253)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animalapp.Animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
