# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cat', serialize=False, to='animalapp.Animal'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dog', serialize=False, to='animalapp.Animal'),
        ),
    ]
