# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.AddField(
            model_name='animal',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(choices=[('dsh', 'Domestic shorthair/mix'), ('persian', 'Persian'), ('siamese', 'Siamese')], default='dsh', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='intake_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
