# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0002_auto_20170801_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='breed',
            new_name='cat_breed',
        ),
        migrations.RenameField(
            model_name='dog',
            old_name='personality',
            new_name='dog_personality',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='color',
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_color',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black'), ('tabby', 'tabby'), ('seal point', 'seal point')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_personality',
            field=models.CharField(blank=True, choices=[('sociable and outgoing', 'sociable and outgoing'), ('a bit shy in the shelter environment', 'a bit shy in the shelter environment')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_breed',
            field=models.CharField(blank=True, choices=[('Terrier/Mix', 'Terrier/Mix'), ('Chihuahua', 'Chihuahua'), ('Shepherd/Mix', 'Shepherd/Mix')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_color',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, choices=[('dog', 'dog'), ('cat', 'cat')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='', max_length=50),
        ),
    ]
