# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0002_auto_20170802_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
