# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0002_auto_20170728_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(choices=[('dsh', 'Domestic shorthair/mix'), ('persian', 'Persian'), ('siamese', 'Siamese')], default='Domestic shorthair/mix', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('av', 'available'), ('temp', 'temporarily unavailable'), ('oh', 'on hold'), ('adt', 'ADOPTED')], default='available', max_length=20),
        ),
    ]
