# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0003_auto_20170728_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(choices=[('Domestic shorthair/mix', 'Domestic shorthair/mix'), ('Persian', 'Persian'), ('Siamese', 'Siamese')], default='Domestic shorthair/mix', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('temporarily unavailable', 'temporarily unavailable'), ('on hold', 'on hold'), ('ADOPTED', 'ADOPTED')], default='available', max_length=20),
        ),
    ]
