# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:31
from __future__ import unicode_literals

import animalapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0003_auto_20170808_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=animalapp.models.upload_pet_image)),
                ('alt', models.CharField(default='', max_length=255, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalapp.Animal')),
            ],
        ),
    ]
