# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 17:44
from __future__ import unicode_literals

import animalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FileField(upload_to=animalapp.models.upload_pet_image),
        ),
    ]
