# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0005_auto_20170809_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_personality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('playful', 'playful'), ('sociable and outgoing', 'sociable and outgoing'), ('independent', 'independent'), ('a bit shy in the shelter environment', 'a bit shy in the shelter environment'), ('loves to be around people', 'loves to be around people')], default='', max_length=104),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_personality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('playful', 'playful'), ('friendly and affectionate', 'friendly and affectionate'), ('sociable and outgoing', 'sociable and outgoing'), ('profoundly loyal', 'profoundly loyal')], default='', max_length=72),
        ),
        migrations.AlterField(
            model_name='image',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='animalapp.Animal'),
        ),
    ]
