# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0005_animal_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(choices=[('OFOSA shelter', 'OFOSA shelter'), ('PetSmart Tanasbourne', 'PetSmart Tanasbourne'), ('PetSmart Wilsonville', 'PetSmart Wilsonville'), ('PetSmart Cedar Hills', 'PetSmart Cedar Hills'), ('PetSmart Hillsboro', 'PetSmart Hillsboro'), ('Foster home', 'Foster home')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='surgery',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=20, verbose_name='Spayed/neutered'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20, verbose_name='Vaccinated'),
        ),
    ]
