# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 23:04
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0006_auto_20170809_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('black', 'black'), ('brown', 'brown'), ('tan', 'tan'), ('white', 'white')], default='', max_length=21),
        ),
    ]
