# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('animalapp', '0008_auto_20170810_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.CharField(choices=[('American Shorthair', 'American Shorthair'), ('Birman', 'Birman'), ('Domestic Shorthair/Mix', 'Domestic Shorthair/Mix'), ('Maine Coon', 'Maine Coon'), ('Oriental', 'Oriental'), ('Persian', 'Persian'), ('Ragdoll', 'Ragdoll'), ('Siamese', 'Siamese'), ('Siamese/Mix', 'Siamese/Mix'), ('Sphynx', 'Sphynx')], default='Domestic Shorthair/Mix', max_length=50),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_personality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('very playful', 'very playful'), ('sociable and outgoing', 'sociable and outgoing'), ('cuddly and affectionate', 'cuddly and affectionate'), ('independent', 'independent'), ('calm', 'calm'), ('a bit shy in the shelter environment', 'a bit shy in the shelter environment'), ('loves to be around people', 'loves to be around people'), ('adores brushing', 'adores brushing'), ('needs a quiet home', 'needs a quiet home'), ('needs love and consistency', 'needs love and consistency'), ('appreciates lots of attention', 'appreciates lots of attention'), ('talkative', 'talkative'), ('not shy about looking for attention', 'not shy about looking for attention'), ('sweet and gentle', 'sweet and gentle')], default='', max_length=293),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_personality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('friendly and affectionate', 'friendly and affectionate'), ('sociable and outgoing', 'sociable and outgoing'), ('profoundly loyal', 'profoundly loyal'), ('house-trained', 'house-trained'), ('cuddly and affectionate', 'cuddly and affectionate'), ('frequent training sessions', 'frequent training sessions'), ('friendly toward strangers', 'friendly toward strangers'), ('has a quiet, laid-back temperament', 'has a quiet, laid-back temperament'), ('loves running around and playing', 'loves running around and playing'), ('not very fond of the outdoors', 'not very fond of the outdoors')], default='', max_length=253),
        ),
    ]
