# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import portfoliopages.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopages', '0008_auto_20170720_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=portfoliopages.models.profile_upload_handler)),
            ],
        ),
    ]
