# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopages', '0016_auto_20170821_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=models.TextField(max_length=700),
        ),
    ]
